Repository shubhxg/web-dev-journey, pull requests merged in 2023-06, with the labels that each got.

#14 Update CSS notes
  CSS/readme.md
Labels: documentation, enhancement

#15 improves readability
  Git/readme.md
Labels: documentation, enhancement

#16 [docs] semantic elements add
  CSS/readme.md
  HTML/readme.md
Labels: documentation, enhancement

#21 [docs] Updated Git Notes
  Git/readme.md
Labels: documentation, enhancement

#22 [fix] Imrpoved pr template
  .github/pull-request-template.md
Labels: enhancement

#25 Update README.md
  README.md
Labels: enhancement, design

#31 docs update api/readme.md
  APIs/readme.md
Labels: documentation, enhancement
